- hosts: master
  sudo: yes
  tasks:
    - name: apt-get update
      apt: update_cache=yes
    - name: install mysql
      apt: pkg={{ item }}
      with_items:
        - mysql-server
        - mysql-client
    - name: install PowerDNS
      apt: pkg={{ item }}
      with_items:
        - pdns-server
        - pdns-backend-mysql
