---
- name: local
  hosts: 127.0.0.1
  connection: local
  sudo: no
  roles:
    - local

- name: master
  hosts: master
  sudo: yes
  roles:
    - common
    - master

- name: slave-bind
  hosts: slave-bind
  sudo: yes
  roles:
    - common
    - slave-bind

- name: slave-knotdns
  hosts: slave-knotdns
  sudo: yes
  roles:
    - common
    - slave-knotdns
