---
- name: local
  hosts: 127.0.0.1
  connection: local
  sudo: no
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - local

- name: master
  hosts: master
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - master

- name: slave-bind
  hosts: slave-bind
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-bind

- name: slave-knotdns
  hosts: slave-knotdns
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-knotdns

- name: slave-nsd
  hosts: slave-nsd
  sudo: yes
  vars_files:
    - vars/{{ env }}.yml
  roles:
    - common
    - slave-nsd
