---
- name: local
  hosts: local
  sudo: no
  roles:
    - local

- name: master
  hosts: master
  sudo: yes
  roles:
    - common
    - master

- name: slave
  hosts: slave
  sudo: yes
  roles:
    - common
    - slave
