- name: install depences
  apt: pkg={{ item }}
  with_items:
    - bind9
    - daemontools
- name: copy bind9 config file
  copy: src=etc/bind/named.conf.options
        dest=/etc/bind/named.conf.options
- name: make zones directory
  file: path=/var/cache/bind/slave state=directory
        owner=bind
- name: reload bind9
  service: name=bind9 state=reloaded
- name: get publickey
  shell: cat /home/{{ opsuser }}/.ssh/id_rsa.pub
  register: slave_publickey
- name: set publickey to master
  shell: echo '{{ slave_publickey.stdout }}' >> /home/{{ opsuser }}/.ssh/authorized_keys
  delegate_to: "{{ master }}"
